### ISSUE TITLE
where should documentation on how to write new tactics etc live

### ISSUE THREAD

**Issue by cartazio** [leanprover/reference#6]
the new icfp 2017 paper on lean alludes to some cool stuff on that front, but theres no much documentation on how to do that, and its certainly different from how tactics are typically written in coq :)

**Comment by jroesch** [comment]
The reference manual initiative got side tracked by some other unexpected priorities at MSR. We were trying to port most of the goodies for our existing `mkleanbook` repository to GitBook to reduce the amount of code we need to maintain. I hope to ship a fully functional version of this in the next couple days, and then we should be able to add documentation here with executable examples. 

Particularly on the tactic documentation front I think the goal is to use this new book infrastructure to write both `Lean by Example` and have this explain things at the reference manual level of detail.

**Comment by avigad** [comment]
It will go in Chapter 6.
